// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd5cMYItg6echWWPGV7jNNO4CX-HnHWXw',
    appId: '1:280969731842:web:4a0c8444cc900af4902c1b',
    messagingSenderId: '280969731842',
    projectId: 'ferdiansyah76-2df0b',
    authDomain: 'ferdiansyah76-2df0b.firebaseapp.com',
    storageBucket: 'ferdiansyah76-2df0b.firebasestorage.app',
    measurementId: 'G-TSYQF9598S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlWTeOcTZcW0rK5Vh76EjGVD1kr54UqNM',
    appId: '1:280969731842:android:4b2692d9bd94b877902c1b',
    messagingSenderId: '280969731842',
    projectId: 'ferdiansyah76-2df0b',
    storageBucket: 'ferdiansyah76-2df0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEoofNYXFwdu_rwpY_mUSWgwz_sPr7jXs',
    appId: '1:280969731842:ios:eb131468a493233f902c1b',
    messagingSenderId: '280969731842',
    projectId: 'ferdiansyah76-2df0b',
    storageBucket: 'ferdiansyah76-2df0b.firebasestorage.app',
    iosBundleId: 'com.example.merchandise48',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEoofNYXFwdu_rwpY_mUSWgwz_sPr7jXs',
    appId: '1:280969731842:ios:eb131468a493233f902c1b',
    messagingSenderId: '280969731842',
    projectId: 'ferdiansyah76-2df0b',
    storageBucket: 'ferdiansyah76-2df0b.firebasestorage.app',
    iosBundleId: 'com.example.merchandise48',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkQAc8o6jwxKUNuZLxQSsKL8wSrftyAIA',
    appId: '1:280969731842:web:0de1a42141c0e385902c1b',
    messagingSenderId: '280969731842',
    projectId: 'ferdiansyah76-2df0b',
    authDomain: 'ferdiansyah76-2df0b.firebaseapp.com',
    storageBucket: 'ferdiansyah76-2df0b.firebasestorage.app',
    measurementId: 'G-LBYQVR5T3V',
  );
}
